### PR TITLE
Drop 7.0, 7.1

### PR DESCRIPTION
**Pull request by notkriswagner**
PHP has dropped support for 7.0 and 7.1. This is just to update the docs and test jobs to drop 7.0 and 7.1 testing

### CODE REVIEW

**Comment by notkriswagner** [comment]
@smtakeda can you review this?

**Comment by snowstakeda** [comment]
Please update the README as well.

**Comment by notkriswagner** [comment]
> Please update the README as well.

It is updated

**Comment by notkriswagner** [comment]
Yup there is a JIRA to add PHP 7.3 and 7.4 testing

**Pull request merged**
